# streamlit_app.py
# Simple Streamlit UI for CodeViz.
#
# Run:
#   streamlit run streamlit_app.py

import os
import sys
import uuid
import tempfile
import streamlit as st
import pandas as pd

# ── Make sure agents folder is on the path ────────────────────────────────────
AGENTS_DIR = os.path.join(os.path.dirname(__file__), 'agents')
if AGENTS_DIR not in sys.path:
    sys.path.insert(0, AGENTS_DIR)

from main import run_analysis_programmatic

# ══════════════════════════════════════════════════════════════════════════════
#  PAGE CONFIG
# ══════════════════════════════════════════════════════════════════════════════

st.set_page_config(
    page_title="CodeViz: Multi-Agent Data Science System",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
    <style>
    .main-header {
        font-size: 2.2rem;
        font-weight: bold;
        color: #1f77b4;
        text-align: center;
        padding: 1rem 0;
    }
    .sub-header {
        font-size: 1.2rem;
        font-weight: 600;
        color: #2c3e50;
        margin-top: 1rem;
        margin-bottom: 0.5rem;
    }
    </style>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════════════════════
#  RESULTS DIR
# ══════════════════════════════════════════════════════════════════════════════

RESULTS_DIR = os.path.join(os.path.dirname(__file__), 'results')
os.makedirs(RESULTS_DIR, exist_ok=True)

# ══════════════════════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def load_dataset_from_upload(uploaded_file) -> pd.DataFrame:
    ext = os.path.splitext(uploaded_file.name)[1].lower()
    if ext == '.csv':
        return pd.read_csv(uploaded_file)
    elif ext in ['.xlsx', '.xls']:
        return pd.read_excel(uploaded_file)
    elif ext == '.json':
        return pd.read_json(uploaded_file)
    elif ext == '.parquet':
        return pd.read_parquet(uploaded_file)
    else:
        raise ValueError(f"Unsupported file format: {ext}")


def display_results(output: dict):
    """Display pipeline results in a clean layout."""

    # Compute stats directly from task_results
    task_results = output.get('task_results', [])
    errors       = output.get('errors', [])

    # ── Subtasks ──────────────────────────────────────────────────────────────
    subtasks = output.get('subtasks', [])
    if subtasks:
        with st.expander("**Subtasks Generated by Planner**", expanded=True):
            for i, t in enumerate(subtasks, 1):
                desc    = t.get('description', str(t)) if isinstance(t, dict) else str(t)
                ml_step = t.get('ml_step') if isinstance(t, dict) else None
                tag     = f" `[{ml_step}]`" if ml_step else ""
                st.markdown(f"**{i}.** {desc}{tag}")

    st.markdown("---")

    # ── Task results ──────────────────────────────────────────────────────────
    if task_results:
        st.markdown("<div class='sub-header'>Task Outputs</div>",
                    unsafe_allow_html=True)

        for idx, t in enumerate(task_results, 1):
            task     = t.get('task', '')
            ok       = t.get('ok', False)
            result   = t.get('result')
            error    = t.get('error')
            code     = t.get('code')
            attempts = t.get('attempts', 1)

            label = f"Task {idx}: {task[:80]}{'...' if len(task) > 80 else ''}"

            with st.expander(f"**{label}**", expanded=ok):
                col1, col2 = st.columns([3, 1])
                with col1:
                    st.write(f"**Agent:** {t.get('agent', '')}")
                    if attempts > 1:
                        st.caption(f"Succeeded after {attempts} attempt(s)")
                with col2:
                    if ok:
                        st.success("✓ Success")
                    else:
                        st.error("✗ Failed")

                if ok and result is not None:
                    if isinstance(result, dict):
                        # Check if it's a visualization result with a file
                        file_path = result.get('file')
                        if file_path and os.path.exists(file_path):
                            st.image(file_path, use_container_width=True)
                        elif file_path and os.path.exists('output.png'):
                            st.image('output.png', use_container_width=True)
                        else:
                            st.json(result)
                    elif isinstance(result, pd.DataFrame):
                        st.dataframe(result, use_container_width=True)
                    else:
                        st.write(result)

                if error:
                    st.error(f"**Error:** {error}")

                if code:
                    with st.expander("View Generated Code"):
                        st.code(code, language='python')

    # ── Errors ────────────────────────────────────────────────────────────────
    if errors:
        st.markdown("---")
        st.markdown("<div class='sub-header'>Pipeline Errors</div>",
                    unsafe_allow_html=True)
        for e in errors:
            st.error(f"**{e.get('task', e.get('stage', 'Unknown'))}**: {e.get('error', '')}")

# ══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════════════════════════════════════

def main():
    st.markdown("<div class='main-header'>CodeViz: Multi-Agent Data Science System</div>",
                unsafe_allow_html=True)
    st.markdown("Upload a dataset, describe your problem, and CodeViz will automatically "
                "plan, generate, and execute the full data science pipeline.")
    st.markdown("---")

    # ── Session state ─────────────────────────────────────────────────────────
    if 'df' not in st.session_state:
        st.session_state.df = None
    if 'dataset_name' not in st.session_state:
        st.session_state.dataset_name = None
    if 'analysis_complete' not in st.session_state:
        st.session_state.analysis_complete = False
    if 'results' not in st.session_state:
        st.session_state.results = None

    # ── Sidebar ───────────────────────────────────────────────────────────────
    with st.sidebar:
        st.header("Configuration")

        st.subheader("1. Upload Dataset")
        uploaded_file = st.file_uploader(
            "Choose a file",
            type=['csv', 'xlsx', 'xls', 'json', 'parquet'],
            help="Supported formats: CSV, Excel, JSON, Parquet"
        )

        if uploaded_file is not None:
            try:
                st.session_state.df = load_dataset_from_upload(uploaded_file)
                st.session_state.dataset_name = uploaded_file.name
                st.session_state.analysis_complete = False
                st.success(f"Loaded: {uploaded_file.name}")
            except Exception as e:
                st.error(f"Error loading file: {str(e)}")
                st.session_state.df = None

        if st.session_state.df is not None:
            df = st.session_state.df
            st.markdown("---")
            st.subheader("Dataset Info")
            st.write(f"**Rows:** {df.shape[0]:,}")
            st.write(f"**Columns:** {df.shape[1]}")
            st.write(f"**Columns:** {', '.join(df.columns[:5].tolist())}"
                     + (f" ... +{df.shape[1]-5} more" if df.shape[1] > 5 else ""))

        st.markdown("---")
        use_rag = st.toggle("Use RAG", value=True,
                            help="Enable RAG-augmented planning")

    # ── Main content ──────────────────────────────────────────────────────────
    if st.session_state.df is None:
        st.info("Please upload a dataset to begin.")
        st.markdown("### How it works")
        st.markdown("""
        1. **Upload** your CSV or Excel dataset
        2. **Describe** your data science problem in plain English
        3. **Run** the pipeline (CodeViz plans, generates, and executes the pipeline)
        4. **View** the results, generated code, and metric scores
        """)
        return

    df = st.session_state.df

    # Dataset preview
    st.markdown("### Dataset Preview")
    st.dataframe(df.head(10), use_container_width=True)
    st.markdown("---")

    # Problem statement
    st.markdown("### Problem Statement")
    problem_statement = st.text_area(
        "Describe what you want to do:",
        placeholder=(
            "Example: Train a regression model to predict gemstone price "
            "and report the RMSE score."
        ),
        height=100,
        label_visibility="collapsed"
    )

    st.markdown("---")
    col1, col2 = st.columns([1, 4])
    with col1:
        run_button = st.button("Run Pipeline", type="primary",
                               use_container_width=True,
                               disabled=not bool(problem_statement))
        with col2:
            if st.button("Reset", use_container_width=False):
                st.session_state.analysis_complete = False
                st.session_state.results = None
                st.rerun()

        if run_button:
            st.session_state.analysis_complete = False
            st.session_state.results = None

            # Save uploaded df to a temp CSV for run_analysis_programmatic
            with tempfile.NamedTemporaryFile(
                delete=False, suffix='.csv', mode='w', encoding='utf-8'
            ) as tmp:
                df.to_csv(tmp, index=False)
                tmp_path = tmp.name

            run_name = f"ui_run_{uuid.uuid4().hex[:8]}"

            with st.spinner("Running CodeViz pipeline... this may take 30-90 seconds."):
                try:
                    output = run_analysis_programmatic(
                        dataset_path=tmp_path,
                        problem_statement=problem_statement,
                        use_rag=use_rag,
                        verbose=False,
                        test_case_name=run_name,
                        results_dir=RESULTS_DIR,
                    )
                    st.session_state.results = output
                    st.session_state.analysis_complete = True
                except Exception as e:
                    st.error(f"Pipeline error: {str(e)}")
                finally:
                    if os.path.exists(tmp_path):
                        os.remove(tmp_path)

            if st.session_state.analysis_complete:
                errors = st.session_state.results.get('errors', [])
                if errors:
                    st.warning("Pipeline completed with errors. See details below.")
                else:
                    st.success("Pipeline complete!")
                #st.rerun()

    # Display results
    if st.session_state.analysis_complete and st.session_state.results:
        st.markdown("---")
        display_results(st.session_state.results)


if __name__ == "__main__":
    main()